---
- name: Escape dot in the ip adresss
  ansible.builtin.set_fact:
    _ip_regex:
      "{{ item.ip | regex_replace('\.', '\.' ) }}"

- name: Display the ip_regex var
  ansible.builtin.debug:
    msg:
      - '_ip = {{ _ip_regex }}'
  tags:
    - never
    - debug

- name: "Update /etc/hosts {{ item.ip }} {{ item.name }}"
  ansible.builtin.lineinfile:
    path: /etc/hosts
    state: "{{ item.state | default('present') }}"
    line: "{{ item.ip }} {{ item.name }}"
    regexp: "^{{ _ip_regex }}\\s+{{ item.name }}"
